#!/bin/bash

# WBF Platform - CloudFront Setup Script
# This script creates a CloudFront distribution for the admin panel

set -e

BUCKET_NAME="portal.wbfpartnership.com"
DOMAIN_NAME="portal.wbfpartnership.com"
REGION="eu-north-1"
AWS_PROFILE="wbf"

echo "================================================"
echo "WBF Platform - CloudFront Setup"
echo "================================================"

echo ""
echo "🔍 Checking for existing CloudFront distributions..."

# Get S3 website endpoint
S3_WEBSITE_ENDPOINT="${BUCKET_NAME}.s3-website-${REGION}.amazonaws.com"

echo ""
echo "================================================"
echo "⚠️  MANUAL CLOUDFRONT SETUP REQUIRED"
echo "================================================"
echo ""
echo "Please follow these steps in AWS Console:"
echo ""
echo "1. Go to CloudFront Console:"
echo "   https://console.aws.amazon.com/cloudfront/v3/home"
echo ""
echo "2. Click 'Create Distribution'"
echo ""
echo "3. Origin Settings:"
echo "   - Origin domain: ${S3_WEBSITE_ENDPOINT}"
echo "   - Protocol: HTTP only"
echo "   - Name: ${BUCKET_NAME}"
echo ""
echo "4. Default Cache Behavior:"
echo "   - Viewer Protocol Policy: Redirect HTTP to HTTPS"
echo "   - Allowed HTTP Methods: GET, HEAD, OPTIONS"
echo "   - Cache Policy: CachingOptimized"
echo ""
echo "5. Settings:"
echo "   - Alternate domain names (CNAMEs): ${DOMAIN_NAME}"
echo "   - SSL Certificate: Request or import certificate for ${DOMAIN_NAME}"
echo "   - Default root object: index.html"
echo "   - Custom error responses:"
echo "     * 404 -> /index.html (200)"
echo "     * 403 -> /index.html (200)"
echo ""
echo "6. After creation, note the CloudFront domain (e.g., d1234abcd.cloudfront.net)"
echo ""
echo "7. Update Route 53 DNS:"
echo "   - Create CNAME record: ${DOMAIN_NAME} -> [CloudFront domain]"
echo "   OR"
echo "   - Create A record (Alias): ${DOMAIN_NAME} -> [CloudFront distribution]"
echo ""
echo "================================================"
echo ""
echo "📋 SSL Certificate Steps (if needed):"
echo ""
echo "1. Go to AWS Certificate Manager (us-east-1 region for CloudFront):"
echo "   https://console.aws.amazon.com/acm/home?region=us-east-1"
echo ""
echo "2. Request certificate for: ${DOMAIN_NAME}"
echo ""
echo "3. Validate via DNS (add CNAME record in Route 53)"
echo ""
echo "4. Once validated, select it in CloudFront settings"
echo ""
echo "================================================"
